services:
  mysql:
    image: mysql:8.0
    container_name: vehicle2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehiclemanage
    ports:
      - '3307:3306' # host:container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-proot']
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: vehiclemanage:latest
    container_name: vehicle2-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vehiclemanage?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - '8080:8080'

volumes:
  mysql_data:
